on:
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      # ...
      # ...
      validate-policy-bot-config: ${{ steps.changes.outputs.policy-bot == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
        id: changes
        with:
          list-files: json
          filters: |
            policy-bot:
              - '.policy.yml'

  validate-policy-bot-config:
    name: Validate policy-bot Configuration
    needs: setup
    if: needs.setup.outputs.validate-policy-bot-config == 'true'
    uses: coopnorge/github-workflow-policy-bot-config-validation/.github/workflows/policy-bot-config-validation.yaml@v0
    permissions:
      contents: read
    secrets:
      policy-bot-server-url: ${{ secrets.POLICY_BOT_BASE_URL }}
  
  build:
    needs:
      - validate-policy-bot-config
    permissions: {}
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - run: exit 1
        name: "Catch errors"
        if: ${{ contains(join(needs.*.result, ','), 'failure') || contains(join(needs.*.result, ','), 'cancelled') }}

